const validInstructions = {
  cargue: { check: "checkVariableOperations" },
  almacene: { check: "checkVariableOperations" },
  nueva: { check: "declareVariables" },
  etiqueta: { check: "declareTags" },
  lea: { check: "checkVariableOperations" },
  sume: { check: "checkVariableOperations" },
  reste: { check: "checkVariableOperations" },
  multiplique: { check: "checkVariableOperations" },
  divida: { check: "checkVariableOperations" },
  potencia: { check: "checkVariableOperations" },
  modulo: { check: "checkVariableOperations" },
  concatene: { check: "checkVariableOperations" },
  elimine: { check: "checkVariableOperations" },
  extraiga: { check: "checkExtraiga" },
  Y: { check: "checkExtraiga" },
  O: { check: "checkLogicalOperation" },
  NO: { check: "checkLogicalOperation" },
  menor: { check: "checkLogicalOperation" },
  mayor: { check: "checkLogicalOperation" },
  igual: { check: "checkLogicalOperation" },
  muestre: { check: "checkVariableOperations" },
  imprima: { check: "checkVariableOperations" },
  vaya: { check: "checkVaya" },
  vayasi: { check: "checkVayaSi" },
  retorne: { check: "checkRetorne" },
}

/*const validString = {
  cargue: "cargue",
  almacene: "almacene",
  nueva: "nueva",
  etiqueta: "etiqueta",
  lea: "lea",
  sume: "sume",
  reste: "reste",
  multiplique: "multiplique",
  divida: "divida",
  potencia: "potencia",
  modulo: "modulo",
  concatene: "concatene",
  elimine: "elimine",
  extraiga: "extraiga",
  Y: "Y",
  O: "O",
  NO: "NO",
  menor: "menor",
  mayor: "mayor",
  igual: "igual",
  muestre: "muestre",
  imprima: "imprima",
  vaya: "vaya",
  vayasi: "vayasi",
  retorne: "retorne",
}*/

const validTypeVariables = {
  I: true,
  R: true,
  C: true,
  L: true,
}

const propertyProgram = {
  name: "name",
  state: "state",
  codeSize: "codeSize",
  acumulator: "acumulator",
  codeIndexCurrent: "codeIndexCurrent",
  variables: "variables",
  tags: "tags",
  code: "code",
  errors: "errors",
}

const statusProgram = {
  ready: "ready",
  running: "running",
  stopped: "stopped",
  finished: "finished",
  loading: "loading",
  wrong: "wrong",
}

export { validInstructions, propertyProgram, validTypeVariables, statusProgram }
